spring:
  application:
    name: O1-OrderService
    
  datasource:
    url: jdbc:mysql://mysql:3306/orders_db
    username: root
    password: Raheman123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

